Merge main to master
hrustim25/renderer3d pull request #1
Opened 2023-05-15 18:08 UTC by hrustim25

2023-05-22 12:03 UTC, DimaTrushin requested changes
Сделал несколько замечаний. Обрати внимание, что я не повторял замечание, если видел аналогичную ошибку. Это все надо будет поправить.
Есть несколько глобальных огрехов в организации кода. Но есть и низкоуровневые косяки с отсутствием raii.

2023-05-22 12:03 UTC, DimaTrushin commented on .gitignore
> +build/
Кирпичи. Даже git ругается на отсутствие новых строк в конце  файлов. Добавь везде, чтобы не было кирпичей в глоаза пользователя твоего репозитория.

2023-05-22 12:03 UTC, DimaTrushin commented on setup.sh
У тебя скрипт linux зависимый, об этом стоит написать в readme или добавить скрипт для других систем.

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.h
> +
Не пиши в global namespace. Оберни все в какое-нибудь пространство имен. Тебе линкер потом спасибо скажет. И вообще надо иметь эту привычку, потому что в больших проектах ты помрешь разбираться с ошибками линковки.

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.h
> +    const unsigned SCREEN_WIDTH_ = 800;
- В таком стиле пишут только макросы, имена констант обычно начинают с буквы k или можно добавить слово default. Например k_screen_width_ или default_screen_width_.
- Используй static constexpr unsigned int. Раз это абсолютная константа, то тебе нет смысла хранить ее в каждой instance объекта. А так как это примитивный класс, то можно сделать constexpr и тогда у тебя все заинлайнится. Кроме того, не используй неявный int, пиши типы явно.

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.h
> +    Space& GetSpace();
- Если используешь функции доступа к полям, которые возвращают неконстантную ссылку, то лучшье не использовать get в названии, так как get обычно не влияет на поля класса.
- Кроме того, такой доступ выглядит как ошибка дизайна. Зачем тебе напрямую доступ к полям класса? Почему их конструирование не происходит сразу в конструкторе Renderer?

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.h
> +    void SetFillMode(bool is_texture_mode);
Плохое название функции, не понятно, что это значит.
Кроме того, bool флаги -- это плохо, дело в том, что не понятно что ты хочешь сказать значением true. Тебе это надо отражать в имени переменной. Вместо этого используй
```cpp
enum class TextureMode {
NoTexture, UseTexture
};
```
Что-то в таком духе, тогда будет более понятно, что делает функция, даже если ее имя не самое удачное.

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.h
> +    Rasterizer rasterizer_;
1) Если нужны дефолтные значения, то можешь их прям тут и прописывать
```cpp
Rasteraizer  rasterizer_ = Rasterizer(SCREEN_WIDTH_, SCREEN_HEIGHT_, camera_);
```
2) Не понятно, почему нет дефолтных значений у камеры и space.
3) Плохо, что rasterizer_ принимает camera_. Это уже говорит о плохих зависимостях. Он может отрисовывать только в одну камеру, ее нельзя менять, ее нельзя переключить на другой экран-вью. В целом это всегда признак ошибки дизайна.

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.h
> +    Matrix4 transformation_matrix_;
Почему эта штука не инициализируется ни в одном конструкторе?

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.h
> +    void Start();
Вот эта функция сразу говорит об ошибке дизайна. У тебя Renderer занимается не своей работой. Есть renderer, а есть  application. Так вот функция start должна быть у объекта application. Он хранит все необходимое для функционирования внутри себя. Он хранит все ресурся, он сам их в своем конструкторе создает и работает с ними. Если тебе нужно создать несколько демонстраций, то я бы создал несколько application объектов. А общую логику запихнул бы в базовый объект по методу policy based design.
```cpp
class BaseApplication {
public:
  BaseApplication(); // инициализация sfml ресурсов
  void Start(); // запуск event loop-а
private:
};
```
А далее, унаследовать от него разные другие application
```cpp
class ApplicatoinCube : public BaseApplication {
public:
  ApplicationCube(); // инициализация всего для работы с кубом
 // функция Start() уже по хорошему есть, если ее надо настроить можно пользоваться виртуальными методами.
private:
  Cube cube_;
};
```

Либо есть другой подход. 
```cpp
template<class T>
class Application : T {
public:
  Application();
};

class CubeResources {
// имплементация ресурсов
};

class ApplicationCube : public Application<CubeResources> {};
```
Тогда тебе надо в Application сделать единый метод доступа к ресурсам, чтобы их инициализировать и работать с ними.

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.h
> +class Renderer {
В целом это не Renderer, это именно Application. Задача Renderer -- перевести 3D сцену в изображение экрана и все. А уже задача view объектов отрисовать это самое изображение.

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.cpp
> +}
Вот эти конструкторы создают тебе не полностью инициализированный объект. Это ошибка дизайна. Задача конструктора -- полностью инициализировать объект. У тебя не инициализируются камера и space. Вообще space по хорошему не должно храниться в renderer, как и камера. Они должны передаваться ему во время отрисовки.

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.cpp
> +}
А у тебя допустимо использовать Renderer до вызова этой функции? Если нет, то это часть конструктора.

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.cpp
> +            change_matrix = CreateMoveMatrix(0, 0, -0.5);
Волшебные константы. Плюс имя не говорит о том, что за направление ты используешь.

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.cpp
> +    sf::RenderWindow window(sf::VideoMode(SCREEN_WIDTH_, SCREEN_HEIGHT_), "3D Renderer",
Странно, что window создается при запуске start. Я бы рассматривал его как переменную внутри Application. То есть запуск этой функции у тебя создает локальный ресурс, который не виден внутри других методов Application (который у тебя Renderer). Более того, эта инициализация должна быть в конструкторе.

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.cpp
> +    window.setFramerateLimit(60);
И это тоже часть конструктора.

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.cpp
> +    while (window.isOpen()) {
Во-первых, сам цикл очень здоровый.
Во-вторых, у тебя 5 вложенных scope-ов. Даже в ядре линукса разрешено максимум 3.
Все это говорит об ошибке дизайна и необходимости рефакторинга.
В-третьих, у тебя явно нарушение уровня абстракции, ты делаешь высокоуровневую работу рядом с низкоуровневой. Подробнее ниже.

По-хорошему идеальный цикл выглядит как-то так
```cpp
while (window.isOpen()) {
  handle_sfml_events(); // камера обнавляется тут
  update_scene(); // позиции объектов обновляются тут
  Image image = renderer_.render(space_, camera_);
  window_.draw(image);
}
```
Ты не должен тут задумываться над всякими мелкими деталями.

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.cpp
> +        }
Судя по всему, вот это это просто обработка почтового ящика sfml. Это выглядит как отдельная функция.

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.cpp
> +        window.clear();
Ты не должен очищать window явно. window должна съедать твою картинку и сама уметь все рисовать. В частности она сама должна знать когда ей там что очищать в своих ресурсах. Это не задача пользователя window всем этим заниматься. По хорошему оберни window в объект а-ля View и сделай в нем метод, который съедает экран и отрисовывает его. И ты больше ни о чем не заботишься.

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.cpp
> +        }
1) Слишком низкоуровневая работу.
2) Не понятно, почему у space_ нет метода transformAllPoints(...), который принимает transformation_matrix_ и трансформирует все точки сразу? Более того, наличие transformPoint сомнительно, не может ли это поломать тебе инварианты, если ты трансформировал часть точек, а другую нет?
Переделать.

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.cpp
> +        }
Я правильно понимаю, что ты отдельно трансформируешь точки, и отдельно привязанные к ним нормали? Если так, то это ты вынул кишки метода. По сути вызов любой из этих функций отдельно ломает инварианты объекта. У тебя должен быть единый метод трансформации в сцене, который применяет нужную трансформацию ко всему и не ломает сцену.

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.cpp
> +        space_.AddNormal(Vertex::GetLightDirection());
Это что за хрень? Почему у тебя каждый цикл в сцену что-то добавляется?

2023-05-22 12:03 UTC, DimaTrushin commented on src/renderer.cpp
> +        rasterizer_.Clear();
Растеризатор должен быть частью renderer и должен работать на этапе переработки 3D сцены в изображение. Тут ему не место. Тем более не место его очищению и не место коду ниже, который явно занимается какой-то низкоуровневой работой.
Код ниже надо весь унести внутрь метод растеризации.

2023-05-22 12:03 UTC, DimaTrushin commented on src/space.cpp
> +Space::Polygon Space::GetPolygon(unsigned index) const {
Почему не по константной ссылке?

2023-05-22 12:03 UTC, DimaTrushin commented on src/space.h
> +    void TransformNormal(unsigned index, const Matrix4& transformation_matrix);
Вот это вглядит как будто ты ломаешь инварианты, если независимо трансформируешь точки и нормали.

2023-05-22 12:03 UTC, DimaTrushin commented on src/space.h
> +    uint32_t GetColor(unsigned index) const;
Я правильно понимаю, что это просто возможность поменять у одной точки, которая уже есть какие-то свойства?

2023-05-22 12:03 UTC, DimaTrushin commented on src/space.h
> +    void AddPoint(const Point4& point);
А количество точек, нормалей, цветов как-то согласовано? Если да, то этот метод ломает инварианты класса.
В целом тут какая-то каша в этом классе из методов. Надо определеиться, что ты тут вообще хочешь делать. Выпиши мне инварианты класса, как данные согласованы.

2023-05-22 12:03 UTC, DimaTrushin commented on src/space.cpp
> +}
Никогда не делай так. Вместо этого внутри класса напиши Space() = default;

2023-05-22 12:03 UTC, DimaTrushin commented on src/space.cpp
> +    polygons_.reserve(expected_size);
Судя по всему, тут все таки есть какие-то инварианты. Но у тебя конструктор как обычно не до конца конструирует объект.

2023-05-22 12:03 UTC, DimaTrushin commented on src/space.cpp
> +Vector4 Space::NormalizeVector(const Vector4& vec) {
Этому методу не место тут. Это метод для работы с векторами. Либо его надо поместить в статические методы тут, либо надо запихнуть в Vector в качестве статического метода, либо если это 3d party class, то сделать функцию в соответствующем namespace и вызывать ее.

2023-05-22 12:03 UTC, DimaTrushin commented on src/space.cpp
> +    return {vec(0) / length, vec(1) / length, vec(2) / length, vec(3)};
А при этом 4-ю координату мы не хотим 1 сделать?

2023-05-22 12:03 UTC, DimaTrushin commented on src/rasterizer.h
> +    std::unique_ptr<long double[]> zbuffer_;
Если тебе нужен буффер, то есть более приличное название для него -- std::vector<long double>. Это избавит тебя от менеджмента памяти.

2023-05-22 12:03 UTC, DimaTrushin commented on src/rasterizer.h
> +    const Camera& camera_;
Зачем надо хранить ссылку на камеру? Почему нельзя передавать ее в качестве аргумента в метод draw? Кроме того, мне казалось, что растерайзер уже работает в нормализованных координатах и потому нет вообще необходимости знать камеру.

2023-05-22 12:03 UTC, DimaTrushin commented on src/rasterizer.h
> +    void Clear();
Вот этого метода быть не должно в публичном интерфейсе.

2023-05-22 12:03 UTC, DimaTrushin commented on src/rasterizer.h
> +    const uint32_t* GetPixelArray() const;
Судя по всему ты отрисовываешь в буффере первым методом, а потом получаешь к нему доступ во втором. Вместо этого хорошо бы иметь метод вида
```cpp
Image image = rasterizer.draw(...);
```
Которому передаем все, что надо для растеризации и он сразу выкатывает нам картинку.

2023-05-22 12:03 UTC, DimaTrushin commented on src/rasterizer.cpp
> +    zbuffer_ = std::make_unique<long double[]>(screen_width * screen_height);
Вообще можешь сделать класс поверх вектора, который по индексам i, j умеет получать доступ к нужному пикселю в буффере, например color_buffer_(i, j) и не надо будет танцев с бубнами при работе с элементами буффера.

2023-05-22 12:03 UTC, DimaTrushin commented on src/rasterizer.cpp
> +        zbuffer_[i] = 1e18;
волшебные константы.

2023-05-22 12:03 UTC, DimaTrushin commented on src/rasterizer.cpp
> +}
Плохое название. Это не нормализация. Это явно проекция на карту.

2023-05-22 12:03 UTC, DimaTrushin commented on src/rasterizer.cpp
> +long double GetTriangleArea(const Vertex &vertex1, const Vertex &vertex2, const Vertex &vertex3) {
Это не метод для rasterizer-а. И уж точно не публичный.

2023-05-22 12:03 UTC, DimaTrushin commented on src/rasterizer.cpp
> +uint32_t ApplyBrightness(uint32_t color, long double brightness) {
Не уверен, что это метод для rasterizer

2023-05-22 12:03 UTC, DimaTrushin commented on src/rasterizer.cpp
> +long double NormalizeTextureCoordinate(long double coord) {
Почему текстура сама об этом не беспокоится?

2023-05-22 12:03 UTC, DimaTrushin commented on src/rasterizer.cpp
> +
Выглядит так, что выше делается какой-то предрасчет, а ниже цикл. Можно ли этим блокам дать нормальные названия?

2023-05-22 12:03 UTC, DimaTrushin commented on src/rasterizer.cpp
> +            if (is_texture_mode_) {
4 вложенных scope => рефактор.

2023-05-22 12:03 UTC, DimaTrushin commented on src/rasterizer.cpp
> +    left_edge.InitialStep(first_y);
Что за названия Step() и InitialStep()? Что ты хочешь сделать?

2023-05-22 12:03 UTC, DimaTrushin commented on src/rasterizer.cpp
> +    long long mid_y = std::min((long double)SCREEN_HEIGHT_, std::ceil(vertex2.GetPoint()(1)));
Си касты -- бан. Если тебе нужны касты, то это скорее всего из-за того, что тебе надо преобразовать непрерывные координаты в дискретные и наоборот. Почему ты не сделаешь функции вроде screen_height() которая возвращает long double.
Кроме того, у тебя std::min делается в long double, а потом результат складывается в long long. Что очень подозрительно. Что вообще ты тут делаешь?

2023-05-22 12:03 UTC, DimaTrushin commented on src/rasterizer.cpp
> +    edge23.SetMode(is_texture_mode_);
Почему нельзя mode передать в конструкторе? Пусть этот метод остается, но почему в конструкторе не съедать его сразу?

2023-05-22 12:03 UTC, DimaTrushin commented on src/rasterizer.cpp
> +    int type = GetTriangleArea(vertex1, vertex2, vertex3) >= 0;
woh, bool to int конвертация. Какого хера?

2023-05-22 12:03 UTC, DimaTrushin commented on src/rasterizer.cpp
> +bool Rasterizer::IsTriangleVisible(const Point4 &point1, const Point4 &point2,
По хорошему это какой-то фильтрующий объект должен делать, когда составляет данные для растерайзера.

2023-05-22 12:03 UTC, DimaTrushin commented on src/rasterizer.cpp
> +    if (!IsTriangleVisible(camera_.ToLocalCoordinates(vertex1.GetPoint()),
Вот такие длинные вызовы объектов друг через друга выглядят уродливо. Но чтобы это изменить, надо все перелопачивать. Потому я пока просто вздохну.

2023-05-22 12:03 UTC, DimaTrushin commented on test/test_cube.cpp
> +    renderer.SetRotationMatrix(rm);
Вот эта штука говорит, что у тебя не до конца создается рендерер. Ты создаешь его сырым, а потом пытаешься досоздать снаружи. Это ошибка дизайна.

2023-05-22 12:03 UTC, DimaTrushin commented on test/test_cube.cpp
> +    Point4 points[8];
Код от 12 до 42 выглядит как инициализация сцены. Почему это не делается в конструкторе сцены?

2023-05-22 12:03 UTC, DimaTrushin commented on test/test_cube.cpp
> +    renderer.Start();
Это выглядит как запуск приложения Application, а не использование renderer-а.

2023-05-22 12:03 UTC, DimaTrushin commented on src/primitives/vertex.h
> +    static Vector4 light_direction_;
Wow. Неконстантное статическое данное. С меня сейчас десять потов сошло.
Какого хрена вообще есть глобальный источник света привязанный ко всем вершинам на свете? Это ошибка дизайна. Убрать отсуда и вынести наружу в источники света.

Вообще, vertex сейчас нельзя использовать в конструкторах глобальных объектов. В целом я бы предпочитал Scott Mayers singlton в таких случаях
```cpp
static Vector4& LightDirection () {
  static Vector4 light_direction = {-1, 0, 0, 0};
  return light_direction;
}
```
А еще лучше убрать вообще глобальный ресурс, когда он тут нафиг не нужен.

2023-05-22 12:03 UTC, DimaTrushin commented on src/primitives/vertex.h
> +    const Image* texture_ = nullptr;
Я всегда с подозрением отношусь к указателям. Но как минимум тут указатель на константный объект. У тебя предусматривается корректное поведение класса, когда указатель nullptr?

2023-05-22 12:03 UTC, DimaTrushin commented on src/primitives/vertex.h
> +private:
А у тебя есть хоть какие-то инварианты на эти данные? Выглядит так, что можно сделать структуру и не любить мозг классом и методами доступа.

2023-05-22 12:03 UTC, DimaTrushin commented on src/primitives/vertex.cpp
> +Vertex::Vertex() : color_(255) {
Если сделать структуру вместо класса, то тебе не нужно делать миллион конструкторов. У тебя будет aggregate initialization напрямую всех полей и за счет дефолтных значений все остальные тоже заполнятся как надо.

2023-05-22 12:03 UTC, DimaTrushin commented on src/primitives/vertex.cpp
> +    return {((long double)GetColorPart(0)) / 256, ((long double)GetColorPart(1)) / 256,
замени Си касты на static_cast

2023-05-22 12:03 UTC, DimaTrushin commented on src/primitives/matrix.h
> +    }
А это точно нужно? Это как-то супер контринтуитивно.

2023-05-22 12:03 UTC, DimaTrushin commented on src/primitives/matrix.h
> +    friend Matrix<X, Y> operator*(const Matrix<X, Y>& matrix, long double coefficient);
- Зачем ты делаешь друга для другого размера матрицы?
- Делай друзей inline без шаблонов.
- А ты хочешь умножать только с одной стороны? Почему не сделать сразу оба оператора умножения слева и справа?

2023-05-22 12:03 UTC, DimaTrushin commented on src/primitives/matrix.h
> +        }
Это скоре assert, чем exception, ибо это программист налажал. И потом, ты нигде не перехватываешь exception в main функции. Это черевато.
Кроме того, вот тут уж было бы неплохо сделать template, потому что ты умножаешь на матрицу того же размера, а хочешь умножать на матрицу совместимого размера.

2023-05-22 12:03 UTC, DimaTrushin commented on src/primitives/matrix.h
> +    Matrix<M, N> Transpose() const {
Это несколько плохой подход. Когда ты пишешь
```cpp
Matrix x;
x.transpose();
```
То кажется, что ты транспонируешь in place. Да у тебя это не получится, если N != M, но тем не менее, это контринтуитивно. Лучше сделай статический метод, который принимает матрицу на вход.

2023-05-22 12:03 UTC, DimaTrushin commented on src/primitives/matrix.h
> +    Matrix<N, K> result_matrix;
Переделай через operator*=

2023-05-22 12:03 UTC, DimaTrushin commented on src/primitives/edge.h
> +class Edge {
Очень странный класс. С очень странным названием. Судя по всему это какая-то версия итератора для отрисовки растерайзером.

2023-05-22 12:03 UTC, DimaTrushin commented on src/primitives/edge.h
> +    void Step();
Почему так странно. Выглядит так, что в начальное состаяние должен инициализировать конструктора, а в последующее состояние оператор next() (или ++).

2023-05-22 12:03 UTC, DimaTrushin commented on src/camera.h
> +class Camera : public Pivot {
А ты уверен, что это хорошая идея наследовать camera от pivot? Я к тому, что все ли методы публичного интерфейса от Pivot имеют смысл для Camera? Это первый вопрос. Второй вопрос, надо ли согласовывать с состоянием Pivot другие данные в камере? Если на первый вопрос ответ да, а на второй -- нет, то все ОК.

2023-05-22 12:03 UTC, DimaTrushin commented on src/camera.h
> +    Camera(unsigned screen_width, unsigned screen_height);
А поменять разрешение камеры мы потом не можем?

2023-05-22 12:03 UTC, DimaTrushin commented on src/camera.h
> +    Point4 ProjectToScreen(const Point4& point) const;
Почему результат проекции вектор размера 4?

2023-05-22 12:03 UTC, DimaTrushin commented on src/camera.h
> +    long double clip_distance_ = 800.0;
волшебные константы.

2023-05-22 12:03 UTC, DimaTrushin commented on src/camera.h
> +    long double view_piramid_height_tan;
нет _ в конце имени.

2023-05-22 12:03 UTC, DimaTrushin commented on src/camera.cpp
> +    view_piramid_height_tan = (long double)screen_height_ / 2 / clip_distance_;
почему не в списке инициализации?

2023-05-22 12:03 UTC, DimaTrushin commented on src/camera.cpp
> +    return {new_x, new_y, local_point(2), 1};
Я бы возвращал вектор длины 3.

2023-05-22 12:03 UTC, DimaTrushin commented on src/image.h
> +    RGB& GetPixel(int y, int x);
Вот тут лучше сделать метод Pixel(int y, int x). Чтобы было видно, что мы меняем это поле.

2023-05-22 12:03 UTC, DimaTrushin commented on src/image.h
> +    void SetPixel(int y, int x, const RGB& pixel);
Почему такой странный порядок координат? Сначала y потом x?

2023-05-22 12:03 UTC, DimaTrushin commented on src/image.h
> +    void ReadBmp(const std::string& filename);
Поидее Image не должен уметь себя читать из разных форматов. Он должен уметь сериализоваться, но формат -- это вопрос открытия файлового потока. Этим должны заниматься отдельные объекты.

2023-05-22 12:03 UTC, DimaTrushin commented on src/image.h
> +    std::vector<std::vector<RGB>> data_;
Плохо делать вектор векторов.
Во-первых, ты не можешь гарантировать что внутренние вектора имеют единую длинну.
Во-вторых, у тебя нет локализованности по памяти.

Сделай единый буффер на основе std::vector<RGB> и добавь нормальный доступ с помощью перегрузки operator(int y, int x).

2023-05-22 12:03 UTC, DimaTrushin commented on src/image.cpp
> +    unsigned char* data = new unsigned char[full_width];
а что стало с std::vector<unsigned char>? Плюс у тебя не RAII и любое исключение влечет утечку.

2023-05-22 12:03 UTC, DimaTrushin commented on src/image.cpp
> +    FILE* infile = fopen(filename.c_str(), "rb");
Никогда не используй напрямую fonep и fclose. Потому что это не совместимо с исключениями. Любое исключение и у тебя зависнет в системе занятый файл. Оборачивай это в class. Или используй файловый поток ifstream или ofstream.

2023-05-22 12:03 UTC, DimaTrushin commented on src/image.cpp
> +    png_destroy_read_struct(&png_ptr, &info_ptr, NULL);
Нарушение RAII, в случае исключений, этот ресурс не почистится, это надо заворачивать в raii обертку.

2023-05-22 12:03 UTC, DimaTrushin commented on src/image.cpp
> +}
А какое поведение ты ожидаешь на незнакомый формат?

2023-05-22 12:03 UTC, DimaTrushin commented on src/object_reader.h
> +    ObjectReader();
Конструктор тут тебе не нужен.

2023-05-22 12:03 UTC, DimaTrushin commented on src/object_reader.h
> +    Object3d ReadObject(const std::string& filename, Space& space) const;
- У тебя нет внутреннего состояния, почему метод не статический?
- Почему space передается по неконстантной ссылке? Если ты хочешь его менять, то лучше передавать по указателю, так пользователь метода будет понимать, что space меняется. Такую идеологию использует scanf, например scanf(&x) говорит тебе о том, что x явно тут будут менять.
- Название метода плохое. Как я понял, ты загружаешь метод в Space, а потом из него возвращаешь некий proxy объект. Мне в целом дизайн не нравится, но я пока не готов сказать, как надо.

2023-06-02 20:12 UTC, hrustim25 commented on src/primitives/vertex.h
> +    const Image* texture_ = nullptr;
Да, сейчас если указатель равен nullptr, то треугольник заполняется цветами, иначе текстурой.

2023-06-02 20:27 UTC, hrustim25 commented on src/primitives/matrix.h
> +    }
Это сделано, чтобы обращение к вектору выглядело более понятно. В новых коммитах добавил static_assert, чтобы длина одной стороны была 1.

2023-06-02 20:36 UTC, hrustim25 commented on src/primitives/matrix.h
> +        }
А если делать через шаблон, разве не получится, что в матрицу NxM нужно сохранить матрицу NxK?

2023-06-02 20:40 UTC, hrustim25 commented on src/primitives/edge.h
> +class Edge {
Да, это итератор по параметрам пикселей вдоль ребра треугольника.

2023-06-02 21:12 UTC, hrustim25 commented on src/camera.h
> +class Camera : public Pivot {
Камера смотрит в направлении оси Z, так чтобы ось Y проходила наверх, поэтому при обновлении pivot данные камеры уже согласованы. Из методов не используется только обратное преобразование координат.

2023-06-02 21:40 UTC, hrustim25 commented on src/camera.h
> +    Point4 ProjectToScreen(const Point4& point) const;
Эту точку дальше нужно положить в контейнер вершины треугольника, которая хранит точку в том числе в однородных координатах, поэтому вектор длины 3 придется обратно увеличивать до 4.

2023-06-02 22:21 UTC, hrustim25 commented on src/space.h
> +    void AddPoint(const Point4& point);
Не согласовано. Каждый треугольник ссылается на тройки параметров, которые могут быть везде разными, но могут и быть общими между треугольниками. В формате obj так же.

2024-01-20 13:40 UTC, closed without merging